version: "3.8"

services:
  demo-db-spark-minio-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  spark-runner:
    build:
      context: .
      dockerfile: Dockerfile.spark
    depends_on:
      - demo-db-spark-minio-postgres
      - minio
    volumes:
      - .:/app
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    working_dir: /app

volumes:
  pg_data:
  minio_data:
