name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: [parquet, csv]
        partitioned: [true, false]

    env:
      FORMAT: ${{ matrix.format }}
      PARTITIONED: ${{ matrix.partitioned }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -U pip
        pip install -e .[dev]

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --cov=sqlxport --cov-config=.coveragerc

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
