# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -U pip
        pip install -e .[dev]

    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        pytest --cov=sql2data --cov-config=.coveragerc

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

